language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
script:
  - npm run build
deploy:
  provider: npm
  email: eddimensi@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
    repo: dimensi/vue-slide-toggle
