language: node_js
node_js:
  - 10
cache:
  directories:
    - ~/.npm
    - ~/.cache
script:
  - npm run test
  - npm run build
deploy:
  provider: npm
  email: eddimensi@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
    repo: dimensi/vue-slide-toggle
